import streamlit as st
import numpy as np

# 1. CORE VISUAL WINDOW SETUP
st.set_page_config(layout="wide", page_title="Portfolio Testing Panel")

# 2. RAW FIXED DATASET MATRIX (ALL 48 GLOBAL SEMICONDUCTOR ASSETS)
RAW_DATA = [
    {"category": "Magnificent Seven", "name": "Nvidia Corp.", "ticker": "NVDA", "currency": "USD", "price": 135.50, "ann_10y": 0.452, "vol": 0.44, "industry": "AI Compute / GPUs", "geo": "USA"},
    {"category": "Magnificent Seven", "name": "Microsoft Corp.", "ticker": "MSFT", "currency": "USD", "price": 420.10, "ann_10y": 0.245, "vol": 0.22, "industry": "Enterprise Software / Cloud", "geo": "USA"},
    {"category": "Magnificent Seven", "name": "Apple Inc.", "ticker": "AAPL", "currency": "USD", "price": 225.40, "ann_10y": 0.221, "vol": 0.20, "industry": "Consumer Hardware / Mobile", "geo": "USA"},
    {"category": "Magnificent Seven", "name": "Alphabet Inc.", "ticker": "GOOGL", "currency": "USD", "price": 175.60, "ann_10y": 0.195, "vol": 0.24, "industry": "Digital Advertising / AI", "geo": "USA"},
    {"category": "Magnificent Seven", "name": "Amazon.com Inc.", "ticker": "AMZN", "currency": "USD", "price": 185.30, "ann_10y": 0.212, "vol": 0.28, "industry": "E-Commerce / Cloud Infrastructure", "geo": "USA"},
    {"category": "Magnificent Seven", "name": "Meta Platforms Inc.", "ticker": "META", "currency": "USD", "price": 495.20, "ann_10y": 0.228, "vol": 0.36, "industry": "Digital Advertising / Metaverse", "geo": "USA"},
    {"category": "Magnificent Seven", "name": "Tesla Inc.", "ticker": "TSLA", "currency": "USD", "price": 210.50, "ann_10y": 0.384, "vol": 0.52, "industry": "Automotive / Energy Storage", "geo": "USA"},
    {"category": "SOXX Top 15 Holdings", "name": "Advanced Micro Devices", "ticker": "AMD", "currency": "USD", "price": 154.40, "ann_10y": 0.315, "vol": 0.42, "industry": "AI Compute / CPUs", "geo": "USA"},
    {"category": "SOXX Top 15 Holdings", "name": "Micron Technology, Inc.", "ticker": "MU", "currency": "USD", "price": 94.50, "ann_10y": 0.198, "vol": 0.49, "industry": "Memory (HBM / DRAM)", "geo": "USA"},
    {"category": "SOXX Top 15 Holdings", "name": "Broadcom Inc.", "ticker": "AVGO", "currency": "USD", "price": 164.80, "ann_10y": 0.294, "vol": 0.27, "industry": "Networking / ASICs", "geo": "USA"},
    {"category": "SOXX Top 15 Holdings", "name": "Applied Materials, Inc.", "ticker": "AMAT", "currency": "USD", "price": 192.40, "ann_10y": 0.264, "vol": 0.34, "industry": "Wafer Fab Equipment", "geo": "USA"},
    {"category": "SOXX Top 15 Holdings", "name": "Intel Corporation", "ticker": "INTC", "currency": "USD", "price": 28.10, "ann_10y": 0.012, "vol": 0.39, "industry": "IDM / Foundry Transition", "geo": "USA"},
    {"category": "SOXX Top 15 Holdings", "name": "KLA Corporation", "ticker": "KLAC", "currency": "USD", "price": 685.20, "ann_10y": 0.256, "vol": 0.31, "industry": "Process Diagnostics Equipment", "geo": "USA"},
    {"category": "SOXX Top 15 Holdings", "name": "Lam Research Corp.", "ticker": "LRCX", "currency": "USD", "price": 842.50, "ann_10y": 0.284, "vol": 0.37, "industry": "Wafer Fab Equipment", "geo": "USA"},
    {"category": "SOXX Top 15 Holdings", "name": "Texas Instruments Inc.", "ticker": "TXN", "currency": "USD", "price": 178.60, "ann_10y": 0.142, "vol": 0.23, "industry": "Analog Nodes / Embedded Chips", "geo": "USA"},
    {"category": "SOXX Top 15 Holdings", "name": "Marvell Technology, Inc.", "ticker": "MRVL", "currency": "USD", "price": 68.20, "ann_10y": 0.201, "vol": 0.41, "industry": "Networking / Infrastructure", "geo": "USA"},
    {"category": "SOXX Top 15 Holdings", "name": "Qualcomm Inc.", "ticker": "QCOM", "currency": "USD", "price": 168.20, "ann_10y": 0.185, "vol": 0.35, "industry": "Mobile Wireless Edge", "geo": "USA"},
    {"category": "SOXX Top 15 Holdings", "name": "Monolithic Power Systems", "ticker": "MPWR", "currency": "USD", "price": 720.40, "ann_10y": 0.312, "vol": 0.33, "industry": "Analog Nodes / Power Systems", "geo": "USA"},
    {"category": "SOXX Top 15 Holdings", "name": "NXP Semiconductors N.V.", "ticker": "NXPI", "currency": "USD", "price": 265.22, "ann_10y": 0.161, "vol": 0.26, "industry": "Analog Nodes / Embedded Chips", "geo": "Netherlands"},
    {"category": "SOXX Top 15 Holdings", "name": "Analog Devices, Inc.", "ticker": "ADI", "currency": "USD", "price": 210.50, "ann_10y": 0.164, "vol": 0.25, "industry": "Analog Nodes / Signal Processing", "geo": "USA"},
    {"category": "Taiwan", "name": "TSMC", "ticker": "TSM", "currency": "USD", "price": 178.20, "ann_10y": 0.261, "vol": 0.33, "industry": "Pure-Play Foundry", "geo": "Taiwan"},
    {"category": "Taiwan", "name": "United Microelectronics", "ticker": "UMC", "currency": "USD", "price": 7.80, "ann_10y": 0.114, "vol": 0.36, "industry": "Pure-Play Foundry", "geo": "Taiwan"},
    {"category": "Taiwan", "name": "Vanguard International", "ticker": "5347.TW", "currency": "TWD", "price": 112.50, "ann_10y": 0.095, "vol": 0.32, "industry": "Pure-Play Foundry", "geo": "Taiwan"},
    {"category": "Taiwan", "name": "MediaTek", "ticker": "2454.TW", "currency": "TWD", "price": 1240.00, "ann_10y": 0.184, "vol": 0.38, "industry": "Mobile Wireless Edge", "geo": "Taiwan"},
    {"category": "Taiwan", "name": "Novatek Microelectronics", "ticker": "3034.TW", "currency": "TWD", "price": 510.00, "ann_10y": 0.141, "vol": 0.30, "industry": "Display Driver ICs", "geo": "Taiwan"},
    {"category": "Taiwan", "name": "Realtek Semiconductor", "ticker": "2379.TW", "currency": "TWD", "price": 485.00, "ann_10y": 0.162, "vol": 0.34, "industry": "Networking / Infrastructure", "geo": "Taiwan"},
    {"category": "Taiwan", "name": "Alchip Technologies", "ticker": "3661.TW", "currency": "TWD", "price": 2450.00, "ann_10y": 0.412, "vol": 0.55, "industry": "Networking / ASICs", "geo": "Taiwan"},
    {"category": "Taiwan", "name": "ASE Technology Holding", "ticker": "ASX", "currency": "USD", "price": 14.50, "ann_10y": 0.124, "vol": 0.29, "industry": "Advanced Node OSAT packaging", "geo": "Taiwan"},
    {"category": "Japan", "name": "Tokyo Electron", "ticker": "8035.T", "currency": "JPY", "price": 24500.00, "ann_10y": 0.231, "vol": 0.36, "industry": "Wafer Fab Equipment", "geo": "Japan"},
    {"category": "Japan", "name": "Advantest Corp.", "ticker": "6857.T", "currency": "JPY", "price": 5800.00, "ann_10y": 0.252, "vol": 0.39, "industry": "Process Diagnostics Equipment", "geo": "Japan"},
    {"category": "Japan", "name": "Disco Corp.", "ticker": "6146.T", "currency": "JPY", "price": 41200.00, "ann_10y": 0.342, "vol": 0.41, "industry": "Wafer Fab Equipment", "geo": "Japan"},
    {"category": "Japan", "name": "Lasertec Corp.", "ticker": "6920.T", "currency": "JPY", "price": 22400.00, "ann_10y": 0.485, "vol": 0.48, "industry": "Process Diagnostics Equipment", "geo": "Japan"},
    {"category": "Japan", "name": "SCREEN Holdings", "ticker": "7735.T", "currency": "JPY", "price": 9800.00, "ann_10y": 0.221, "vol": 0.38, "industry": "Wafer Fab Equipment", "geo": "Japan"},
    {"category": "Japan", "name": "Kokusai Electric", "ticker": "6525.T", "currency": "JPY", "price": 3100.00, "ann_10y": 0.165, "vol": 0.35, "industry": "Wafer Fab Equipment", "geo": "Japan"},
    {"category": "Japan", "name": "Kioxia Holdings", "ticker": "285A.T", "currency": "JPY", "price": 2850.00, "ann_10y": 0.112, "vol": 0.43, "industry": "Memory (HBM / DRAM)", "geo": "Japan"},
    {"category": "Japan", "name": "Renesas Electronics", "ticker": "6723.T", "currency": "JPY", "price": 2450.00, "ann_10y": 0.154, "vol": 0.32, "industry": "Analog Nodes / Embedded Chips", "geo": "Japan"},
    {"category": "Japan", "name": "Ibiden Co.", "ticker": "4062.T", "currency": "JPY", "price": 4800.00, "ann_10y": 0.132, "vol": 0.33, "industry": "Advanced Node OSAT packaging", "geo": "Japan"},
    {"category": "Japan", "name": "ROHM Co.", "ticker": "6963.T", "currency": "JPY", "price": 1850.00, "ann_10y": 0.084, "vol": 0.29, "industry": "Analog Nodes / Power Systems", "geo": "Japan"},
    {"category": "South Korea", "name": "Samsung Electronics", "ticker": "005930.KS", "currency": "KRW", "price": 68500.00, "ann_10y": 0.112, "vol": 0.31, "industry": "IDM Conglomerate", "geo": "South Korea"},
    {"category": "South Korea", "name": "SK Hynix", "ticker": "000660.KS", "currency": "KRW", "price": 165000.00, "ann_10y": 0.214, "vol": 0.42, "industry": "Memory (HBM / DRAM)", "geo": "South Korea"},
    {"category": "Europe", "name": "ASML Holding N.V.", "ticker": "ASML", "currency": "EUR", "price": 820.10, "ann_10y": 0.225, "vol": 0.28, "industry": "Lithography Equipment", "geo": "Netherlands"},
    {"category": "Europe", "name": "Infineon Technologies", "ticker": "IFX", "currency": "EUR", "price": 34.20, "ann_10y": 0.145, "vol": 0.33, "industry": "Analog Nodes / Power Systems", "geo": "Germany"},
    {"category": "Hong Kong Stock Exchange (HKEX)", "name": "SMIC", "ticker": "0981.HK", "currency": "HKD", "price": 22.40, "ann_10y": 0.125, "vol": 0.45, "industry": "Pure-Play Foundry", "geo": "China"},
    {"category": "Hong Kong Stock Exchange (HKEX)", "name": "Hua Hong Semiconductor", "ticker": "1347.HK", "currency": "HKD", "price": 18.50, "ann_10y": 0.091, "vol": 0.41, "industry": "Pure-Play Foundry", "geo": "China"},
    {"category": "Hong Kong Stock Exchange (HKEX)", "name": "Shanghai Fudan Micro", "ticker": "1385.HK", "currency": "HKD", "price": 14.20, "ann_10y": 0.154, "vol": 0.48, "industry": "Analog Nodes / Embedded Chips", "geo": "China"},
    {"category": "Hong Kong Stock Exchange (HKEX)", "name": "InnoScience Technology", "ticker": "2577.HK", "currency": "HKD", "price": 8.50, "ann_10y": 0.050, "vol": 0.50, "industry": "Analog Nodes / Power Systems", "geo": "China"},
    {"category": "Hong Kong Stock Exchange (HKEX)", "name": "Shanghai Biren Technology", "ticker": "6082.HK", "currency": "HKD", "price": 12.10, "ann_10y": 0.060, "vol": 0.55, "industry": "AI Compute / GPUs", "geo": "China"},
